const expect = require('expect.js');
const part1 = require('./part1');
const part2 = require('./part2');

describe('Day 11: Part 1', () => {
  it('Should calculate sum of shortest paths between galaxies', () => {
    expect(part1(
      `...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....`)).to.equal(374);
  });
});
describe('Day 11: Part 2', () => {
  it('Should calculate sum of shortest paths between galaxies with 10 fold expansion', () => {
    expect(part2(
      `...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....`, 10)).to.equal(1030);
  });
});
